# Copyright (C) 2011 Urabe, Shyouhei.  All rights reserved.
#
# This file is  a part of the programming language  Ruby.  Permission is hereby
# granted,  to either  redistribute  or  modify this  file,  provided that  the
# conditions  mentioned in  the file  COPYING are  met.  Consult  the  file for
# details.

# This is  a Travis-CI  build configuration file.   The list  of configurations
# available is located in
#
#     http://about.travis-ci.org/docs/user/build-configuration/
#
# and as Ruby itself is a project written in C language,
#
#     http://about.travis-ci.org/docs/user/languages/c/
#
# is also a good place to look at.

language: c

sudo: false

compiler:
  - gcc

os:
  - linux

git:
  submodules: true

before_install:
  - "CONFIG_FLAG="
  - "JOBS='-j 4'"

before_script:
  - "uname -a"
  - "uname -r"
  - "rm -fr .ext autom4te.cache"
  - "echo $TERM"
  - "make -f common.mk BASERUBY=ruby MAKEDIRS='mkdir -p' srcdir=. update-config_files"
  - "autoconf"
  - "mkdir config_1st config_2nd"
  - "SPEC=linux_x86-64 ./configure -C --with-omr-jit --disable-install-doc --with-gcc=$CC $CONFIG_FLAG" 
  - "make after-update BASERUBY=ruby"
  - "make -s $JOBS"
  - "make librbjit.so"
  - "make update-rubyspec"

script:
  - "make test TESTOPTS=--color=never"
  - "make test-rubyspec MSPECOPT=-fm"
  - "make test-all TESTOPTS='-q -j3 --color=never --job-status=normal'"
  - "OMR_JIT_OPTIONS=-Xjit:count=0 LD_LIBRARY_PATH=$PWD make test TESTOPTS=--color=never"
  - "OMR_JIT_OPTIONS=-Xjit:count=0 LD_LIBRARY_PATH=$PWD make test-rubyspec MSPECOPT=-fm"
  #- "OMR_JIT_OPTIONS=-Xjit:count=0 LD_LIBRARY_PATH=$PWD make test-all TESTOPTS='-q -j3 --color=never --job-status=normal'"
# Local Variables:
# mode: YAML
# coding: utf-8-unix
# indent-tabs-mode: nil
# tab-width: 4
# fill-column: 79
# default-justification: full
# End:
