# Copyright (C) 2011 Urabe, Shyouhei.  All rights reserved.
#
# This file is  a part of the programming language  Ruby.  Permission is hereby
# granted,  to either  redistribute  or  modify this  file,  provided that  the
# conditions  mentioned in  the file  COPYING are  met.  Consult  the  file for
# details.

# This is  a Travis-CI  build configuration file.   The list  of configurations
# available is located in
#
#     http://about.travis-ci.org/docs/user/build-configuration/
#
# and as Ruby itself is a project written in C language,
#
#     http://about.travis-ci.org/docs/user/languages/c/
#
# is also a good place to look at.

# Language specification.
language: c

# Compilers.  Several  compilers are  provided in Travis,  so we try  them all.
# The value set here is visible via $CC environment variable.
compiler:
  - gcc
  - clang 

os:
  - linux
# - osx  # OMR Ruby is not running on OS X yet. 

# https://docs.travis-ci.com/user/caching/
cache: ccache


# These are the same addons as the OMR project itself.
addons:
  apt:
    sources:
       - ubuntu-toolchain-r-test
    packages:
       - libnuma-dev
       - bison
       - gcc-multilib
       - g++-multilib



# Dependencies.  Some  header files are missing  in a Travis' worker  VM, so we
# have  to install  them.  The  "1.9.1" here  is OK.   It is  the  most adopted
# version string  for Debian/Ubuntu, and  no dependencies have been  changed so
# far since the 1.9.1 release.
before_install:
  - "if [[ $TRAVIS_OS_NAME = 'linux' ]]; then sudo apt-get -qq update; fi"
  # Travis ships an outdated, broken version of libssl by default
  - "if [[ $TRAVIS_OS_NAME = 'linux' ]]; then sudo apt-get -qq --only-upgrade install '^libssl.*'; fi"
  - "if [[ $TRAVIS_OS_NAME = 'linux' ]]; then sudo apt-get -qq install $CC; fi" # upgrade if any
  - "if [[ $TRAVIS_OS_NAME = 'linux' ]]; then JOBS='-j'; fi"
  - "if [[ $TRAVIS_OS_NAME = 'osx' ]]; then brew install autoconf openssl; fi"
  - "if [[ $TRAVIS_OS_NAME = 'osx' ]]; then OPENSSL_FLAG=\"--with-openssl-dir=`brew --prefix openssl`\"; fi"
  - "if [[ $TRAVIS_OS_NAME = 'osx' && $CC = 'gcc' ]]; then CC='gcc-4.9'; fi"
install: "if [[ $TRAVIS_OS_NAME = 'linux' ]]; then sudo apt-get -qq build-dep ruby1.9.1 2>/dev/null; fi"

# Script is where the test runs.  Note  we just do "make test", not other tests
# like  test-all, test-rubyspec.   This is  because  they take  too much  time,
# enough for Travis to shut down the VM as being stalled.
before_script:
  - "if [[ $TRAVIS_OS_NAME = 'osx' ]]; then rm -f ~/Library/Logs/DiagnosticReports/ruby_*.crash; fi"
  - "uname -a"
  - "uname -r"
  - "rm -fr .ext autom4te.cache"
  - "make -f common.mk BASERUBY=ruby srcdir=. update-config_files"
  - "autoconf"
  - "mkdir config_1st config_2nd"
  - "SPEC=linux_x86-64 ./configure -C --disable-install-doc --disable-install-rdoc --with-omr-jit --with-gcc=$CC $OPENSSL_FLAG"
  - "make "
script:
  - "OMR_JIT_OPTIONS=-Xjit:count=0 LD_LIBRARY_PATH=$PWD make test"     # JIT test. LD_LIBRARY_PATH is required because we're not installing  
  - "OMR_JIT_OPTIONS=-Xjit:count=0 LD_LIBRARY_PATH=$PWD make test-all" # JIT test-all.
  - "make test"
  - "make test-all"
  - "make test-rubyspec"
after_failure:
  - "if [[ $TRAVIS_OS_NAME = 'osx' ]]; then find ~/Library/Logs/DiagnosticReports -type f -name ruby_\\*.crash -ls -execdir cat {} \\; -delete; fi"

# Local Variables:
# mode: YAML
# coding: utf-8-unix
# indent-tabs-mode: nil
# tab-width: 4
# fill-column: 79
# default-justification: full
# End:
